import type { Model } from "@earendil-works/pi-ai";

const OPENAI_MODELS = {
	"gpt-4o": {
		id: "gpt-4o",
		name: "GPT-4o",
		api: "openai-completions",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: false,
		input: ["text", "image"],
		cost: {
			input: 2.5,
			output: 10,
			cacheRead: 1.25,
			cacheWrite: 0,
		},
		contextWindow: 128000,
		maxTokens: 16384,
		compat: {
			supportsStrictMode: true,
		},
	},
	"gpt-4o-mini": {
		id: "gpt-4o-mini",
		name: "GPT-4o mini",
		api: "openai-completions",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: false,
		input: ["text", "image"],
		cost: {
			input: 0.15,
			output: 0.6,
			cacheRead: 0.075,
			cacheWrite: 0,
		},
		contextWindow: 128000,
		maxTokens: 16384,
		compat: {
			supportsStrictMode: true,
		},
	},
	"gpt-5.4": {
		id: "gpt-5.4",
		name: "GPT-5.4",
		api: "openai-completions",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 2.5,
			output: 15,
			cacheRead: 0.25,
			cacheWrite: 0,
			tiers: [
				{
					inputTokensAbove: 272000,
					input: 5,
					output: 22.5,
					cacheRead: 0.5,
					cacheWrite: 0,
				},
			],
		},
		contextWindow: 272000,
		maxTokens: 128000,
		thinkingLevelMap: {
			off: "none",
			minimal: null,
			low: "low",
			medium: "medium",
			high: "high",
			xhigh: "xhigh",
			max: null,
		},
		compat: {
			supportsStrictMode: true,
			supportsOpenAIGrammarTools: true,
			supportsMidConvoSystemMessages: true,
		},
	},
	"gpt-5.4-mini": {
		id: "gpt-5.4-mini",
		name: "GPT-5.4 mini",
		api: "openai-completions",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.75,
			output: 4.5,
			cacheRead: 0.075,
			cacheWrite: 0,
		},
		contextWindow: 400000,
		maxTokens: 128000,
		thinkingLevelMap: {
			off: "none",
			minimal: null,
			low: "low",
			medium: "medium",
			high: "high",
			xhigh: "xhigh",
			max: null,
		},
		compat: {
			supportsStrictMode: true,
			supportsOpenAIGrammarTools: true,
			supportsMidConvoSystemMessages: true,
		},
	},
	"gpt-5.5": {
		id: "gpt-5.5",
		name: "GPT-5.5",
		api: "openai-completions",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 5,
			output: 30,
			cacheRead: 0.5,
			cacheWrite: 0,
			tiers: [
				{
					inputTokensAbove: 272000,
					input: 10,
					output: 45,
					cacheRead: 1,
					cacheWrite: 0,
				},
			],
		},
		contextWindow: 272000,
		maxTokens: 128000,
		thinkingLevelMap: {
			off: "none",
			minimal: null,
			low: "low",
			medium: "medium",
			high: "high",
			xhigh: "xhigh",
			max: null,
		},
		compat: {
			supportsStrictMode: true,
			supportsOpenAIGrammarTools: true,
			supportsMidConvoSystemMessages: true,
		},
	},
	"gpt-5.6-sol": {
		id: "gpt-5.6-sol",
		name: "GPT-5.6 Sol",
		api: "openai-completions",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 4,
			output: 20,
			cacheRead: 0.4,
			cacheWrite: 5,
			tiers: [
				{
					inputTokensAbove: 272000,
					input: 8,
					output: 30,
					cacheRead: 0.8,
					cacheWrite: 10,
				},
			],
		},
		contextWindow: 272000,
		maxTokens: 128000,
		thinkingLevelMap: {
			off: "none",
			minimal: null,
			low: "low",
			medium: "medium",
			high: "high",
			xhigh: "xhigh",
			max: "max",
		},
		compat: {
			supportsStrictMode: true,
			supportsOpenAIGrammarTools: true,
			supportsMidConvoSystemMessages: true,
		},
	},
	"gpt-5-mini": {
		id: "gpt-5-mini",
		name: "GPT-5 Mini",
		api: "openai-completions",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.25,
			output: 2,
			cacheRead: 0.025,
			cacheWrite: 0,
		},
		contextWindow: 400000,
		maxTokens: 128000,
		thinkingLevelMap: {
			off: null,
			minimal: "minimal",
			low: "low",
			medium: "medium",
			high: "high",
			xhigh: null,
			max: null,
		},
		compat: {
			supportsStrictMode: true,
			supportsOpenAIGrammarTools: true,
		},
	},
} satisfies Record<string, Model<"openai-completions">>;

export type OpenAIModelId = keyof typeof OPENAI_MODELS;

export function openaiModel(id: OpenAIModelId): Model<"openai-completions"> {
	return structuredClone(OPENAI_MODELS[id]) as Model<"openai-completions">;
}
